<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ ucfirst($mode) }} · {{ $brand }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head><body class="auth-body"><a href="/" class="brand"><span class="brand-mark"><x-icon name="spark"/></span>{{ $brand }}</a><div class="auth-layout"><section class="auth-story"><span class="eyebrow">MEET YOUR NEW TEAM MEMBER</span><h1>Your website’s next<br>best salesperson.<span class="orange">Available 24/7.</span></h1><p>Train your AI once. Turn visitor questions into meaningful conversations and qualified leads.</p><div class="story-card"><x-icon name="spark"/><div><strong>Built around your business</strong><p>Your knowledge. Your voice. Your customers.</p></div></div></section><main class="auth-card"><h2>{{ match($mode){'register'=>'Create your account','forgot'=>'Reset your password','reset'=>'Choose a new password',default=>'Welcome back'} }}</h2><p class="muted">{{ $mode==='register'?'Let’s put your website to work.':'Your AI workspace is right here.' }}</p>@if(session('status'))<div class="alert success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ match($mode){'register'=>'/register','forgot'=>'/forgot-password','reset'=>'/reset-password',default=>'/login'} }}" class="form-stack">@csrf
@if($mode==='reset')<input type="hidden" name="token" value="{{ $token }}">@endif
@if($mode==='register')<label>Your name<input name="name" value="{{ old('name') }}" required autocomplete="name"></label>@endif
<label>Email address<input type="email" name="email" value="{{ old('email',$email??'') }}" required autocomplete="email"></label>
@if($mode!=='forgot')<label>Password<input type="password" name="password" required minlength="{{ $mode==='login'?1:10 }}" autocomplete="{{ $mode==='login'?'current-password':'new-password' }}"></label>@endif
@if(in_array($mode,['register','reset']))<label>Confirm password<input type="password" name="password_confirmation" required autocomplete="new-password"></label><small class="muted">Use at least 10 characters, including letters and numbers.</small>@endif
@if($mode==='register')<label class="check-label"><input type="checkbox" name="terms" value="1" required> I agree to the <a href="/terms">terms</a> and <a href="/privacy">privacy policy</a>.</label>@endif
@if($mode==='login')<div class="row-between"><label class="check-label"><input type="checkbox" name="remember" value="1">Remember me</label><a href="/forgot-password" class="text-link">Forgot password?</a></div>@endif
<button class="button primary full">{{ match($mode){'register'=>'Create account','forgot'=>'Send reset link','reset'=>'Update password',default=>'Sign in'} }}<x-icon name="arrow"/></button></form><p class="auth-bottom">{{ $mode==='register'?'Already have an account?':'New to '.$brand.'?' }} <a href="{{ $mode==='register'?'/login':'/register' }}">{{ $mode==='register'?'Sign in':'Get started' }}</a></p></main></div></body></html>
