<section class="installation-platforms" id="platforms">
    <div class="guide-section-heading"><span class="eyebrow">CHOOSE YOUR WEBSITE</span><h2>Where do I paste the code?</h2><p>Use the installation code from your account. Select your platform below.</p></div>
    <div class="platform-guide-grid">
        <details open><summary><span class="platform-letter">W</span><span>WordPress<small>Self-hosted or a plan that allows scripts</small></span><span class="guide-expand">+</span></summary><div><ol><li>Open your WordPress admin and the footer script area provided by your theme or an installed script manager.</li><li>Paste your complete widget code into the site-wide footer scripts field.</li><li>Save, clear your site cache, and open a published page.</li></ol><p>Do not paste it into a regular paragraph block. On WordPress.com, your plan must support custom JavaScript.</p><a href="https://wordpress.com/support/code/" target="_blank" rel="noopener noreferrer">WordPress guidance <x-icon name="arrow"/></a></div></details>
        <details><summary><span class="platform-letter">S</span><span>Shopify<small>Add it to your storefront theme</small></span><span class="guide-expand">+</span></summary><div><ol><li>In Shopify admin, open <strong>Online Store → Themes</strong> and duplicate your theme as a backup.</li><li>Open the theme menu and choose <strong>Edit code</strong>. Find <strong>layout/theme.liquid</strong>.</li><li>Paste your widget code just before <code>&lt;/body&gt;</code>, then save and test your storefront.</li></ol><p>Theme installation is for storefront pages. Shopify checkout has separate restrictions.</p><a href="https://help.shopify.com/en/manual/online-store/themes/customizing-themes/edit-code/edit-theme-code" target="_blank" rel="noopener noreferrer">Shopify guidance <x-icon name="arrow"/></a></div></details>
        <details><summary><span class="platform-letter">W</span><span>Wix<small>Use site-wide Custom Code</small></span><span class="guide-expand">+</span></summary><div><ol><li>Open your site dashboard and find <strong>Settings → Custom Code</strong>.</li><li>Choose <strong>Add Custom Code</strong>, paste the snippet, and give it a name.</li><li>Select <strong>All pages</strong> and <strong>Body – end</strong>. Apply the code and test your published site.</li></ol><p>Your site must meet Wix’s requirements for custom code. Use Custom Code rather than an embedded HTML iframe.</p><a href="https://support.wix.com/en/article/wix-editor-embedding-custom-code-on-your-site" target="_blank" rel="noopener noreferrer">Wix guidance <x-icon name="arrow"/></a></div></details>
        <details><summary><span class="platform-letter">W</span><span>Webflow<small>Use the Footer code field</small></span><span class="guide-expand">+</span></summary><div><ol><li>Open your site’s <strong>Site settings → Custom code</strong>.</li><li>Paste your full widget snippet into <strong>Footer code</strong> and save.</li><li>Publish your site and check the published URL, including on mobile.</li></ol><p>Your Site or Workspace plan must allow custom code. Approve the exact hostname you publish to.</p><a href="https://help.webflow.com/hc/en-us/articles/33961357265299" target="_blank" rel="noopener noreferrer">Webflow guidance <x-icon name="arrow"/></a></div></details>
        <details><summary><span class="platform-letter">R</span><span>React / Next.js<small>Load once in your site’s root layout</small></span><span class="guide-expand">+</span></summary><div><ol><li>For a React app with an HTML entry file, paste the snippet before <code>&lt;/body&gt;</code> in that file.</li><li>For Next.js, use <code>next/script</code> in the root layout with your script URL, <code>data-widget-id</code>, and <code>strategy="afterInteractive"</code>.</li><li>Use your real widget ID, deploy, and test navigation between pages. Load the widget only once.</li></ol><p>Ask your developer to use the exact URL and widget ID from your account. Your API keys are never needed in the embed.</p><a href="https://nextjs.org/docs/app/api-reference/components/script" target="_blank" rel="noopener noreferrer">Next.js Script guidance <x-icon name="arrow"/></a></div></details>
        <details><summary><span class="platform-letter">&lt;/&gt;</span><span>HTML / other websites<small>Any site that supports external JavaScript</small></span><span class="guide-expand">+</span></summary><div><ol><li>Open your website’s shared layout, footer template, or site-wide custom code area.</li><li>Paste the complete snippet before the closing <code>&lt;/body&gt;</code> tag or in the footer scripts field.</li><li>Save and publish. Test a page visitors can access without signing in.</li></ol><p>If your website builder blocks external scripts, ask its support team about custom JavaScript support.</p></div></details>
    </div>
</section>
