<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Turn website visitors into business opportunities with an AI sales assistant. Capture leads, answer questions, request appointments, and automate follow-up."><title>{{ $brand }} · A little AI. A lot more opportunity.</title>@vite(['resources/css/app.css','resources/js/app.js'])<style>:root{--accent:{{ $primaryColor }};--ink:{{ $secondaryColor }}}</style>@if($faviconUrl)<link rel="icon" href="{{ $faviconUrl }}">@endif</head>
<body class="growth-page">
@include('components.marketing-nav')
<main id="main-content">
<section class="growth-hero growth-container">
<div class="growth-hero-copy"><span class="growth-pill"><i></i> BIG IDEAS. SMALL TEAMS. SMARTER GROWTH.</span><h1>More customers.<br>Less busywork.<br><em>Meet your AI assistant.</em></h1><p>Give your website an AI assistant that answers questions, collects customer details, and helps your team follow up. It works from your business information, even when you’re offline.</p><div class="growth-actions"><a href="{{ route('register') }}" class="button primary">Build my free AI agent <x-icon name="arrow"/></a><a href="{{ route('demo') }}" class="button secondary"><x-icon name="chat"/>See it in action</a></div><div class="growth-assurance"><span>✓ No card to get started</span><span>✓ Your knowledge. Your brand.</span></div><div class="growth-hero-foot"><span class="growth-mini-spark">✦</span><p>Less repetitive work.<br><strong>More room for your next big thing.</strong></p></div></div>
<div class="growth-visual" data-auto-demo aria-label="Animated sample: a visitor question becomes a lead and follow-up task">
    <div class="growth-orbit orbit-one"></div><div class="growth-orbit orbit-two"></div><span class="visual-star star-one">✦</span><span class="visual-star star-two">✧</span>
    <div class="growth-chat"><div class="growth-chat-heading"><span class="growth-avatar"><x-icon name="spark"/></span><div><strong>Your AI sales assistant</strong><small><i></i>Always ready to help</small></div><span>•••</span></div>
    <div class="growth-chat-body"><span class="sample-label">AUTOMATIC WALKTHROUGH · SAMPLE CONVERSATION</span>
        <div class="growth-bubble visitor" data-demo-step="0">Hi! I need a website for my business.</div>
        <div class="growth-bubble agent" data-demo-step="1">Happy to help! We build business websites. Would you like our team to contact you?</div>
        <div class="growth-bubble visitor" data-demo-step="2">Yes, I’m Alex. Please email alex@example.com.</div>
        <div class="growth-bubble agent" data-demo-step="3">Thanks, Alex! I’ve shared your enquiry with the team so they can follow up.</div>
        <div class="growth-chat-chips" data-demo-step="4"><span>✓ Lead captured</span><span>✓ Follow-up task created</span></div>
    </div><div class="growth-chat-input"><span data-demo-status>Question → Answer → Lead → Follow-up</span></div><div class="demo-controls" hidden><button type="button" data-demo-toggle aria-pressed="false">Pause demo</button><button type="button" data-demo-replay>Replay <x-icon name="arrow"/></button></div></div>
    <div class="growth-float float-lead"><span class="float-icon"><x-icon name="users"/></span><div><strong>From visitor to opportunity</strong><small>Sample flow · Lead + follow-up task</small></div><span class="float-check">✓</span></div><div class="growth-float float-time"><span class="float-icon"><x-icon name="spark"/></span><div><strong>Open for opportunity</strong><small>Even after closing time</small></div></div>
</div>
</section>
<div class="growth-platforms growth-container"><span>ONE LITTLE SNIPPET. AT HOME ON YOUR WEBSITE.</span><div><strong>WordPress</strong><strong>Shopify</strong><strong>Webflow</strong><strong>Wix</strong><strong>React</strong><strong>Your custom site</strong></div></div>
<section id="features" class="growth-section growth-container"><div class="growth-section-heading"><span class="eyebrow">YOUR GROWTH TOOLKIT</span><h2>Answer questions. Capture leads.<br><em>Keep your business moving.</em></h2><p>Everything you need to help visitors become customers, explained in plain language.</p></div><div class="growth-feature-grid">
<article class="growth-feature feature-wide"><div><span class="growth-feature-icon"><x-icon name="chat"/></span><h3>Make every hello count.</h3><p>Your AI answers from your services, pricing, FAQs, and documents. Help visitors take the next step with answers grounded in your business.</p><a href="{{ route('demo') }}" class="text-link">Meet your next teammate <x-icon name="arrow"/></a></div><img class="growth-automation-image" src="{{ asset('growth-automation.svg') }}" alt="Your website and knowledge connect to an AI assistant that captures leads and creates next steps" width="560" height="290" loading="lazy"></article>
<article class="growth-feature"><span class="growth-feature-icon"><x-icon name="users"/></span><h3>Find the leads that matter.</h3><p>Capture contact details, understand customer needs, and use lead scores to help your team prioritize.</p><div class="growth-lead-art"><span class="lead-avatar">A</span><div><strong>Alex · Website enquiry</strong><small>Interested in your services</small></div><span class="badge green">Qualified</span></div></article>
<article class="growth-feature"><span class="growth-feature-icon"><x-icon name="link"/></span><h3>Keep the momentum going.</h3><p>Tag leads, create tasks, send email alerts, and connect events to your CRM through signed webhooks.</p><div class="growth-flow-art"><span>New lead</span><x-icon name="arrow"/><span>Follow-up task</span></div></article>
<article class="growth-feature"><span class="growth-feature-icon"><x-icon name="calendar"/></span><h3>Turn interest into a next step.</h3><p>Let visitors request appointments in the chat. Your team reviews and confirms the details.</p><div class="growth-appointment-art"><x-icon name="calendar"/><div><strong>Consultation requested</strong><small>Ready for your team to confirm</small></div></div></article>
<article class="growth-feature"><span class="growth-feature-icon"><x-icon name="chart"/></span><h3>See what’s working.</h3><p>Track conversations, lead conversion, and usage from your dashboard. Grow with clearer insight.</p><svg class="growth-chart-art" viewBox="0 0 300 76" role="img" aria-label="Illustration of business activity over time"><path d="M0 70H300 M0 35H300" stroke="#e9e3db" stroke-dasharray="4 5"/><path d="M5 66L40 51L74 58L110 37L147 44L183 20L220 29L260 9L295 15" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/><circle cx="260" cy="9" r="5" fill="currentColor"/></svg></article>
</div></section>
<section id="how-it-works" class="growth-process"><div class="growth-container"><div class="growth-section-heading"><span class="eyebrow">FROM IDEA TO “HELLO”</span><h2>Get started in three simple steps.</h2></div><div class="growth-steps">@foreach([['01','Teach it your business','Import website pages, add FAQs, and share your services and documents.'],['02','Make it feel like you','Choose your widget’s style, greeting, and the details you want to capture.'],['03','Let conversations begin','Install your snippet, test your assistant, and manage new opportunities in your dashboard.']] as [$number,$title,$text])<article><span>{{ $number }}</span><h3>{{ $title }}</h3><p>{{ $text }}</p></article>@endforeach</div><a class="button light process-guide-link" href="{{ route('widget.installation-guide') }}">Follow the full setup guide <x-icon name="arrow"/></a></div></section>
<section id="demo" class="growth-demo growth-container"><div><span class="eyebrow">LESS EXPLAINING. MORE EXPERIENCING.</span><h2>Don’t just imagine it.<br><em>Start a conversation.</em></h2><p>Try the demo agency’s assistant. Ask about website development, SEO, or services and see how your visitors could experience your business.</p><a href="{{ route('demo') }}" class="button primary">Open the live demo <x-icon name="arrow"/></a><small>The walkthrough uses sample data. Use the live demo to try a real conversation.</small><div class="demo-flow-explainer"><span><b>1</b> Visitor asks</span><x-icon name="arrow"/><span><b>2</b> AI answers</span><x-icon name="arrow"/><span><b>3</b> Team follows up</span></div></div><div class="growth-demo-window"><div class="demo-window-bar"><i></i><i></i><i></i><span>YOUR BUSINESS, CONNECTED</span></div><div class="demo-window-body"><div class="demo-sidebar"><x-icon name="spark"/><x-icon name="grid"/><x-icon name="chat"/><x-icon name="users"/><x-icon name="chart"/></div><div class="demo-overview"><span class="sample-label">PRODUCT PREVIEW · SAMPLE DATA</span><h3>A little less busy.<br>A lot more possibility.</h3><div class="demo-stat-row"><div><small>Conversations</small><strong>128</strong></div><div><small>New leads</small><strong>24</strong></div><div><small>Appointments</small><strong>8</strong></div></div><div class="demo-bars">@foreach([28,45,36,62,51,78,65,91,72,100,84,110] as $height)<i style="height:{{ $height }}px"></i>@endforeach</div><div class="demo-lead-row"><span class="lead-avatar">A</span><div><strong>A new opportunity is here.</strong><small>Your next conversation could be the start.</small></div><x-icon name="arrow"/></div></div></div></div></section>
<section id="pricing" class="growth-section growth-container"><div class="growth-section-heading centered"><span class="eyebrow">A PLAN FOR YOUR NEXT CHAPTER</span><h2>Start small. <em>Grow your way.</em></h2><p>Start free, then choose monthly or yearly prepaid access when you’re ready.</p><div class="growth-price-toggle" role="group" aria-label="Pricing interval"><button class="selected" data-price-interval="monthly" aria-pressed="true">Monthly</button><button data-price-interval="yearly" aria-pressed="false">Yearly</button></div></div><div class="growth-pricing-grid">@foreach($plans as $plan)<article @class(['growth-price-card','featured'=>$plan->name==='Professional'])>@if($plan->name==='Professional')<span class="growth-plan-ribbon">ROOM TO GROW</span>@endif<h3>{{ $plan->name }}</h3><p>{{ $plan->monthly_price <= 0 ? 'Get your first conversations going.' : ($plan->name === 'Agency' ? 'Bring your clients along for the journey.' : 'Give your growing business more room.') }}</p><div class="growth-price"><span>{{ $plan->currency === 'INR' ? '₹' : $plan->currency.' ' }}</span><strong data-monthly="{{ number_format($plan->monthly_price) }}" data-yearly="{{ number_format($plan->yearly_price) }}">{{ number_format($plan->monthly_price) }}</strong><small data-price-period>/ month</small></div><a href="{{ route('register') }}" class="button {{ $plan->name==='Professional'?'primary':'secondary' }} full">{{ $plan->monthly_price <= 0 ? 'Start for free' : 'Get '.$plan->name }} <x-icon name="arrow"/></a><ul>@foreach(['conversations'=>'conversations / month','leads'=>'leads / month','team_members'=>'team members','widgets'=>'chat widgets','businesses'=>'businesses'] as $key=>$label)<li><x-icon name="check"/>{{ number_format($plan->limits[$key] ?? 0) }} {{ $label }}</li>@endforeach @if($plan->limits['white_label']??false)<li><x-icon name="check"/>Your own branding</li>@endif</ul></article>@endforeach</div><p class="growth-pricing-note">Pay securely with Razorpay. View billing history and download invoices in your account. Renew manually at the end of your prepaid period.</p></section>
<section class="growth-faq growth-container"><div><span class="eyebrow">GOOD QUESTIONS</span><h2>A few things<br>you might be wondering.</h2></div><div>@foreach([['Do I need to know how to code?','You manage your assistant from the dashboard. Installation uses a small JavaScript snippet that you or your website administrator can add to your site.'],['What does the AI learn from?','Your website pages, documents, FAQs, services, products, and policies. You control the knowledge it can use to answer your customers.'],['Can my team take over a conversation?','Yes. Your team can review conversations and respond from the dashboard when a visitor needs a human.'],['How do subscriptions and invoices work?','Choose a monthly or yearly plan and pay through Razorpay. Access activates after payment verification. You can view your payment history, download paid invoices, and see your expiry countdown in your dashboard. Renewals are manual.']] as [$question,$answer])<details><summary>{{ $question }}<span>+</span></summary><p>{{ $answer }}</p></details>@endforeach</div></section>
<section class="growth-final growth-container"><span>✦</span><div><h2>Your business has a lot to offer.<br>Let’s help more people find it.</h2><p>Your next opportunity starts with a simple hello.</p></div><a href="{{ route('register') }}" class="button light">Build my free agent <x-icon name="arrow"/></a></section>
</main>
@include('components.marketing-footer')
</body></html>
