<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Install your AI chat widget on WordPress, Shopify, Wix, Webflow, React, Next.js, or a custom website. Follow simple setup and testing steps."><title>Install your AI widget · {{ $brand }}</title>@vite(['resources/css/app.css','resources/js/app.js'])<style>:root{--accent:{{ $primaryColor }};--ink:{{ $secondaryColor }}}</style>@if($faviconUrl)<link rel="icon" href="{{ $faviconUrl }}">@endif</head><body class="growth-page guide-page">
@include('components.marketing-nav')
<main id="main-content"><section class="guide-hero growth-container"><div><span class="growth-pill"><i></i> YOUR WEBSITE + YOUR AI ASSISTANT</span><h1>One small snippet.<br><em>A helpful hello on every page.</em></h1><p>Follow this guide to add your AI chat button to a website that supports JavaScript. Your visitors can ask questions and share their details without leaving your site.</p><div class="growth-actions">@auth<a href="{{ url('/installation') }}" class="button primary">Get my installation code <x-icon name="code"/></a>@else<a href="{{ route('register') }}" class="button primary">Create my free account <x-icon name="arrow"/></a>@endauth<a href="#platforms" class="button secondary">Choose my website platform</a></div></div><div class="guide-hero-card"><span class="growth-feature-icon"><x-icon name="chat"/></span><h2>What you’ll need</h2><ul><li><x-icon name="check"/>An account and a business workspace</li><li><x-icon name="check"/>Your website’s exact domain name</li><li><x-icon name="check"/>Access to your website’s code or settings</li><li><x-icon name="check"/>A widget trained with your business information</li></ul><p>No visitor downloads. No API keys in your website code.</p></div></section>
<section class="growth-container guide-setup"><div class="guide-section-heading"><span class="eyebrow">YOUR FIRST SETUP, STEP BY STEP</span><h2>From account to your first conversation.</h2><p>Complete these steps in order. You can ask your website administrator to help with the code step.</p></div><ol class="guide-steps"><li><span>01</span><div><h3>Create your business workspace</h3><p>Sign up, add your business name and website URL, and describe the services you offer.</p></div></li><li><span>02</span><div><h3>Teach your assistant</h3><p>In <strong>AI training</strong>, add your FAQs, services, pricing, or documents. Use <strong>Test your AI</strong> to check answers before you go live.</p></div></li><li><span>03</span><div><h3>Approve your website domain</h3><p>In <strong>Widget design</strong>, add exact hostnames such as <code>example.com</code> and <code>www.example.com</code> separately. Leave out <code>https://</code>, paths, and wildcards. Add staging domains too if your plan has room.</p></div></li><li><span>04</span><div><h3>Copy your own installation code</h3><p>Open <strong>Installation</strong> in your dashboard and click <strong>Copy code</strong> for the widget you want. Each widget has its own ID.</p><div class="guide-code-example"><span>EXAMPLE ONLY — GET YOUR REAL CODE FROM YOUR DASHBOARD</span><pre class="code-block">&lt;script src="{{ url('/widget.js') }}"
        data-widget-id="YOUR_WIDGET_ID"
        defer&gt;&lt;/script&gt;</pre></div></div></li><li><span>05</span><div><h3>Paste, publish, and test</h3><p>Follow your platform’s instructions below. Open your published website, click the chat button, ask a question, and check that the conversation appears in your dashboard.</p></div></li></ol></section>
<div class="growth-container">@include('components.installation-platforms')</div>
<section class="growth-container guide-checklist"><div class="guide-section-heading"><span class="eyebrow">BEFORE YOU SHARE IT WITH CUSTOMERS</span><h2>Your go-live checklist.</h2></div><div class="guide-check-grid">@foreach(['The code is installed once on every page where you want the widget.','Both your bare domain and www domain are approved if your site uses them.','The chat button opens on desktop and mobile.','Your assistant answers a question using your business knowledge.','A test lead and conversation appear in your dashboard.','Your subscription is active and has usage available.'] as $check)<div><x-icon name="check"/><p>{{ $check }}</p></div>@endforeach</div></section>
<section class="growth-container guide-troubleshooting" id="troubleshooting"><div class="guide-section-heading"><span class="eyebrow">NEED A HAND?</span><h2>If something doesn’t look right.</h2></div><div class="guide-help-grid"><article><h3>The chat button is missing</h3><p>Check your script URL and widget ID, confirm the exact hostname is approved, publish your changes, and clear caches. If you use a Content Security Policy, your developer must allow the widget script and its API connections.</p></article><article><h3>The chat opens but answers are limited</h3><p>Add the missing information in AI training, check your subscription and usage, then try the question in the dashboard tester. Your platform administrator can check the AI provider setup.</p></article><article><h3>The homepage check says “not detected”</h3><p>The dashboard check reads your homepage source. Code added by a website builder or JavaScript may appear only after the page loads. Test the live chat manually and check your dashboard conversations.</p></article><article><h3>It works on one domain only</h3><p>Domain approval uses exact hostnames. Add any www, staging, or subdomain you use. A widget should load once per page; remove duplicate snippets if you see repeated behavior.</p></article></div></section>
<section class="growth-final growth-container"><span>✦</span><div><h2>Ready for your first customer hello?</h2><p>Get your widget code and bring your assistant to your website.</p></div><a class="button light" href="{{ auth()->check() ? url('/installation') : route('register') }}">{{ auth()->check() ? 'Open my installation' : 'Start for free' }} <x-icon name="arrow"/></a></section></main>
@include('components.marketing-footer')
</body></html>
