@extends('layouts.app')
@section('title','AI behavior')
@section('content')
<div class="page-heading"><div><span class="eyebrow">A PERSONALITY THAT FITS</span><h1>Your agent. Your rules.</h1><p>Control how your AI talks, qualifies leads, and helps your customers.</p></div></div>
<form action="/chatbot" method="post" class="panel settings-layout">@csrf @method('PUT')<div class="form-section"><h2>Voice & personality</h2><div class="form-grid"><label>Tone<select name="tone">@foreach(['professional','friendly','consultative','concise'] as $tone)<option @selected($settings->tone===$tone)>{{ $tone }}</option>@endforeach</select></label><label>Language<input name="language" value="{{ old('language',$settings->language) }}" required></label><label class="wide">Business instructions<textarea name="instructions" rows="5">{{ old('instructions',$settings->instructions) }}</textarea><small class="field-help">Use verified facts. Safety and privacy rules remain enforced.</small></label></div></div>
<div class="form-section"><h2>Capabilities & privacy</h2><div class="toggle-grid">@foreach(['sales'=>'Sales mode','capture'=>'Lead capture','appointments'=>'Appointment requests','pricing'=>'Disclose verified pricing','handoff'=>'Human handoff','notifications'=>'Email notifications','tracking'=>'Anonymous visitor & campaign tracking'] as $key=>$label)<label class="check-label"><input type="checkbox" name="features[{{ $key }}]" value="1" @checked($settings->features[$key]??false)>{{ $label }}</label>@endforeach</div><label style="margin-top:20px">Conversation retention (days)<input type="number" name="retention_days" min="1" max="3650" value="{{ $settings->retention_days }}" required><small class="field-help">Expired conversations and their messages are deleted by the scheduler.</small></label></div>
<div class="form-section"><h2>Optional lead form fields</h2><div class="toggle-grid">@foreach(['name','email','phone','company','requirement','budget','timeline','service'] as $field)<label class="check-label"><input type="checkbox" name="lead_fields[]" value="{{ $field }}" @checked(in_array($field,$settings->lead_fields,true))>{{ ucfirst($field) }}</label>@endforeach</div><p class="field-help" style="margin-top:15px">Visitors share only what they choose. A phone or email is required to submit the contact form.</p></div>
<div class="form-section"><h2>Lead scoring weights</h2><div class="form-grid">@foreach(config('saas.scoring') as $field=>$weight)<label>{{ ucfirst($field) }}<input type="number" name="scoring[{{ $field }}]" min="0" max="100" required value="{{ $settings->scoring[$field]??$weight }}"></label>@endforeach</div><p class="field-help" style="margin-top:15px">Scores are capped at 100. Cold: 0–29 · Warm: 30–59 · Hot: 60–79 · Very hot: 80–100.</p></div><div class="panel-body"><button class="button primary">Save AI behavior <x-icon name="check"/></button></div></form>
@endsection
