@extends('layouts.app')
@section('title','Overview')
@section('content')
<div class="page-heading"><div><span class="eyebrow">YOUR BUSINESS AT A GLANCE</span><h1>Good to see you, {{ explode(' ',auth()->user()->name)[0] }} <span class="wave">✦</span></h1><p>Here’s how your AI agent is working for your business.</p></div><a href="/tester" class="button primary"><x-icon name="chat"/>Test your AI</a></div>
<div class="agent-banner"><div class="agent-banner-icon"><x-icon name="spark"/></div><div><span class="eyebrow">LESS BUSYWORK. MORE BUSINESS.</span><h2>Your next customer starts with a conversation.</h2><p>Give your AI the knowledge it needs to turn questions into opportunities.</p></div><a href="/training" class="button light">Train your agent <x-icon name="arrow"/></a><div class="banner-decoration">✦</div></div>
<div class="section-caption"><span>Performance overview</span><span class="muted">All time · Live database</span></div>
<div class="stats-grid">@foreach([['Conversations','conversations','chat','Every customer conversation'],['Leads captured','leads','users','New opportunities for your team'],['Qualified leads','qualified','spark','Leads with a score of 60+'],['Conversion rate','conversion','chart','Conversations that became leads']] as [$label,$key,$icon,$detail])<div class="stat-card"><div class="row-between"><span>{{ $label }}</span><span class="stat-icon"><x-icon :name="$icon"/></span></div><strong>{{ number_format($metrics[$key],$key==='conversion'?1:0) }}{{ $key==='conversion'?'%':'' }}</strong><small>{{ $detail }}</small></div>@endforeach</div>
<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><h2>Conversations & leads</h2><p>Your agent’s activity over the last 14 days</p></div><span class="badge neutral">Last 14 days</span></div><div class="chart-legend"><span><i class="orange-dot"></i>Conversations</span><span><i class="dark-dot"></i>Leads</span></div>
@include('business.partials.chart')
<div class="chart-footer"><span>{{ \Carbon\Carbon::parse($daily[0]['date'])->format('d M') }}</span><span>{{ \Carbon\Carbon::parse($daily[6]['date'])->format('d M') }}</span><span>Today</span></div></section>
<section class="panel readiness-panel"><div class="panel-heading"><div><h2>AI readiness</h2><p>A smarter agent starts here</p></div><x-icon name="spark"/></div><div class="readiness-meter" style="--progress:{{ $readiness['score'] }}"><div><strong>{{ $readiness['score'] }}<small>%</small></strong><span>{{ $readiness['score']>90?'Excellent':($readiness['score']>70?'Good':($readiness['score']>40?'Basic':'Needs training')) }}</span></div></div><div class="mini-checks">@foreach(array_slice($readiness['checks'],0,3) as $label=>$done)<div><span @class(['check-circle','done'=>$done])>{{ $done?'✓':'+' }}</span>{{ $label }}<span class="muted">{{ $done?'Added':'Missing' }}</span></div>@endforeach</div><a href="/training" class="button secondary full">Improve AI knowledge <x-icon name="arrow"/></a></section></div>
<section class="panel"><div class="panel-heading"><div><h2>Your priority leads</h2><p>The conversations most likely to become your next customer</p></div><a href="/leads" class="text-link">View all leads <x-icon name="arrow"/></a></div>@include('business.partials.lead-table')</section>
<div class="quick-grid">@foreach([['book','Add business knowledge','Better answers begin with better information.','/manage/knowledge'],['grid','Make it your own','Customize your widget to match your brand.','/widget'],['code','Go live in minutes','One snippet. Any website. Always available.','/installation']] as [$icon,$title,$description,$href])<a href="{{ $href }}" class="quick-card"><span class="stat-icon"><x-icon :name="$icon"/></span><div><h3>{{ $title }}</h3><p>{{ $description }}</p></div><x-icon name="arrow"/></a>@endforeach</div>
@endsection
