<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invoice {{ $invoice['number'] }}</title>
<style>body{font-family:DejaVu Sans,sans-serif;color:#24242b;font-size:12px;margin:40px}h1{font-size:30px;margin:0 0 8px}h2{font-size:15px}p{line-height:1.7}.muted{color:#73737c}.header{border-bottom:3px solid #f97316;padding-bottom:22px}.paid{color:#16734e}table{width:100%;border-collapse:collapse;margin:28px 0}th,td{text-align:left;padding:14px 10px;border-bottom:1px solid #e8e8e8}th{background:#f6f6f6}.total{text-align:right;font-size:18px}.actions{margin-bottom:30px}.actions a{display:inline-block;margin-right:15px;color:#b85212}@media print{.actions{display:none}}</style></head><body>
@unless(request()->boolean('download'))<div class="actions"><a href="{{ route('subscription') }}">Back to billing</a><a href="{{ route('subscription.invoice', ['id' => $payment->id, 'download' => 1]) }}">Download PDF</a></div>@endunless
<div class="header"><h1>Invoice</h1><strong>{{ $invoice['seller'] }}</strong><p>{{ $invoice['number'] }}<br>Issued {{ \Carbon\Carbon::parse($invoice['issued_at'])->format('d M Y') }}<br><span class="paid">PAID · Razorpay</span></p></div>
<h2>Bill to</h2><p>{{ $invoice['billing']['name'] ?? 'Business account' }}<br>{{ $invoice['billing']['email'] ?? '' }}<br>{{ $invoice['billing']['phone'] ?? '' }}<br>{{ $invoice['billing']['address'] ?? '' }}<br>{{ implode(', ', array_filter([$invoice['billing']['city'] ?? '', $invoice['billing']['state'] ?? '', $invoice['billing']['postal_code'] ?? '', $invoice['billing']['country'] ?? ''])) }}@if(!empty($invoice['billing']['tax_id']))<br>Tax ID / GSTIN: {{ $invoice['billing']['tax_id'] }}@endif</p>
<table><thead><tr><th>Description</th><th>Billing period</th><th>Amount</th></tr></thead><tbody><tr><td>{{ $invoice['plan'] }} subscription<br><span class="muted">{{ ucfirst($invoice['interval']) }} prepaid access</span></td><td>@if(isset($invoice['starts_at'], $invoice['ends_at'])){{ \Carbon\Carbon::parse($invoice['starts_at'])->format('d M Y') }}<br>to {{ \Carbon\Carbon::parse($invoice['ends_at'])->format('d M Y') }}@else{{ ucfirst($invoice['interval']) }}@endif</td><td>{{ $payment->currency }} {{ number_format($payment->amount, 2) }}</td></tr></tbody></table>
<p class="total">Total paid: <strong>{{ $payment->currency }} {{ number_format($payment->amount, 2) }}</strong></p>
<p class="muted">Order reference: {{ $payment->reference }}@if(!empty($invoice['payment_id']))<br>Payment reference: {{ $invoice['payment_id'] }}@endif @if(!empty($payment->metadata['coupon_code']))<br>Discount code applied: {{ $payment->metadata['coupon_code'] }}@endif</p><p class="muted">Thank you for your business. Keep this invoice for your billing records.</p>
</body></html>
