@extends('layouts.app')
@section('title','Lead details')
@section('content')
<div class="page-heading"><div><a href="/leads" class="text-link">← Back to leads</a><h1 style="margin-top:12px">{{ $lead->name?:'Website visitor' }}</h1><p>{{ $lead->company?:'Lead captured by your AI agent' }}</p></div><span class="score-pill {{ $lead->temperature }}"><strong class="score-large">{{ $lead->score }}</strong><small>{{ ucwords(str_replace('_',' ',$lead->temperature)) }}</small></span></div>
<div class="detail-grid"><div><section class="panel"><div class="panel-heading"><h2>Customer details</h2><span class="badge neutral">{{ $lead->source }}</span></div><dl class="definition-list panel-body">@foreach(['email','phone','whatsapp','company','service','budget','timeline','location','requirement','recommended_action'] as $field)<div><dt>{{ ucwords(str_replace('_',' ',$field)) }}</dt><dd>{{ $lead->$field?:'Not provided' }}</dd></div>@endforeach</dl></section><section class="panel"><div class="panel-heading"><h2>Conversation summary</h2></div><div class="panel-body"><p style="white-space:pre-wrap;font-size:12px">{{ $lead->summary?:'Close the conversation to generate an AI summary.' }}</p></div></section>
@foreach($lead->sessions as $session)<section class="panel"><div class="panel-heading"><h2>Conversation · {{ $session->created_at->format('d M Y') }}</h2><a href="/conversations?session={{ $session->public_id }}" class="text-link">Open conversation</a></div><div class="message-thread">@foreach($session->messages as $m)<div class="message-bubble {{ $m->sender_type }}"><strong>{{ $m->sender_type }}</strong>{{ $m->message }}</div>@endforeach</div></section>@endforeach
<section class="panel"><div class="panel-heading"><h2>Notes</h2></div><div class="panel-body">@foreach($lead->notes as $note)<div class="record"><strong>{{ $note->author->name }}</strong><p>{{ $note->content }}</p><small class="muted">{{ $note->created_at->diffForHumans() }}</small></div>@endforeach<form method="post" action="/leads/{{ $lead->public_id }}/notes" class="form-stack">@csrf<label>Add a note<textarea name="content" rows="3" required maxlength="5000"></textarea></label><button class="button secondary">Save note</button></form></div></section></div>
<aside><section class="panel"><div class="panel-heading"><h2>Manage this lead</h2></div><form action="/leads/{{ $lead->public_id }}" method="post" class="form-stack panel-body">@csrf @method('PUT')<label>Pipeline status<select name="status">@foreach(['new','contacted','qualified','proposal','won','lost'] as $status)<option @selected($lead->status===$status)>{{ $status }}</option>@endforeach</select></label><label>Assigned to<select name="assigned_user_id"><option value="">Unassigned</option>@foreach($members as $member)<option value="{{ $member->id }}" @selected($lead->assigned_user_id===$member->id)>{{ $member->name }}</option>@endforeach</select></label><label>Tags (comma separated)<input name="tags" value="{{ implode(', ',$lead->tags??[]) }}"></label><button class="button primary">Save lead</button></form></section><section class="panel"><div class="panel-heading"><h2>Activity</h2></div><ul class="timeline panel-body">@foreach($lead->activities->sortByDesc('id') as $activity)<li>{{ $activity->description }}<small>{{ $activity->created_at->diffForHumans() }}</small></li>@endforeach</ul></section><form action="/leads/{{ $lead->public_id }}" method="post" data-confirm="Permanently delete this lead’s data?">@csrf @method('DELETE')<button class="text-link danger">Delete lead data</button></form></aside></div>
@endsection
