@extends('layouts.app')
@section('title',$spec['title'])
@section('content')
<div class="page-heading"><div><span class="eyebrow">{{ in_array($section,['integrations','automations'])?'CONNECTED WORKSPACE':'BUSINESS KNOWLEDGE' }}</span><h1>{{ $spec['title'] }}</h1><p>{{ $spec['description'] }}</p></div><a href="/tester" class="button secondary">Test your AI <x-icon name="arrow"/></a></div>
<div class="resource-grid"><section class="panel"><div class="panel-heading"><h2>{{ $edit?'Edit record':'Add '.($section==='website'?'website':'record') }}</h2>@if($edit)<a href="/manage/{{ $section }}" class="text-link">Cancel edit</a>@endif</div><form class="form-stack panel-body" action="/manage/{{ $section }}{{ $edit?'/'.$edit->id:'' }}" method="post">@csrf @if($edit)@method('PUT')@endif
@foreach($spec['fields'] as $field=>$type)@php($value=old($field,$field==='value'?($edit?->settings['value']??''):($field==='events'?implode(',',$edit?->events??['lead.created','lead.hot']):($edit?->$field??''))))<label>{{ $field==='content'?($section==='faqs'?'Answer':'Information'):ucwords(str_replace('_',' ',$field)) }}
@if($type==='textarea')<textarea name="{{ $field }}" rows="7" required>{{ $value }}</textarea>@elseif(str_starts_with($type,'select:'))<select name="{{ $field }}">@foreach(explode(',',substr($type,7)) as $option)<option value="{{ $option }}" @selected($value===$option)>{{ ucwords(str_replace('_',' ',$option)) }}</option>@endforeach</select>@else<input type="{{ $type }}" name="{{ $field }}" value="{{ $type==='password'?'':$value }}" @if($type==='number') min="0" max="100" @endif @if($type==='password') placeholder="Leave blank to generate or retain a secret" autocomplete="new-password" @endif>@endif</label>@endforeach
@if($section==='website')<p class="field-help">Only import websites you’re authorized to use. The crawler respects robots.txt and your plan’s page limits.</p>@endif
@if($section==='integrations')<p class="field-help">Supported events: lead.created, lead.updated, lead.hot, conversation.completed, appointment.created, human.requested.</p>@endif
<button class="button primary">{{ $section==='website'?'Learn my business':($edit?'Save changes':'Add record') }}<x-icon name="plus"/></button></form></section>
<section class="panel"><div class="panel-heading"><h2>{{ $items->total() }} {{ $section==='website'?'website sources':'records' }}</h2><form method="get"><input name="q" placeholder="Search records…" value="{{ request('q') }}" aria-label="Search records"></form></div><div class="record-list">@forelse($items as $item)<article class="record"><div class="row-between"><strong>{{ $item->title??$item->name??$item->url }}</strong><span class="badge {{ ($item->status??'ready')==='failed'?'red':'green' }}">{{ $item->status??'Active' }}</span></div><p>{{ Str::limit($item->content??($item->trigger??''),160) }}</p>@if($section==='website')<p>{{ $item->pages_crawled }} pages imported · {{ $item->error }}</p>@endif @if($section==='integrations')<p>{{ implode(', ',$item->events) }}</p><details><summary>Show signing secret</summary><code>{{ $item->secret }}</code></details>@endif<div class="record-actions"><a href="/manage/{{ $section }}?edit={{ $item->id }}" class="text-link">{{ $section==='website'?'Re-import':'Edit' }}</a><form method="post" action="/manage/{{ $section }}/{{ $item->id }}" data-confirm="Delete this record?">@csrf @method('DELETE')<button class="text-link danger">Delete</button></form><small class="muted">{{ $item->updated_at->diffForHumans() }}</small></div></article>@empty<div class="empty-state"><x-icon name="book"/><h3>A little knowledge goes a long way</h3><p>Add your first record to get started.</p></div>@endforelse</div><div class="panel-body">{{ $items->links() }}</div></section></div>
@if($section==='knowledge')<section class="panel upload-panel"><div><h2>Bring your documents</h2><p>Upload a text-based PDF or TXT file. Maximum 10 MB.</p></div><form method="post" action="/documents/upload" enctype="multipart/form-data">@csrf<input type="file" name="document" accept=".pdf,.txt" required><button class="button secondary">Import document</button></form></section>@endif
@endsection
